// <auto-generated />
using KoreanSkincareShop.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KoreanSkincareShop.Migrations
{
    [DbContext(typeof(SkincareShopDbContext))]
    [Migration("20260101195529_SeedProducts")]
    partial class SeedProducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KoreanSkincareShop.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsTrendingProduct")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Details = "Regenerująca esencja ze śluzem ślimaka, idealna do skóry wrażliwej.",
                            ImageUrl = "https://example.com/cosrx-snail.jpg",
                            IsTrendingProduct = true,
                            Name = "COSRX Advanced Snail 96 Mucin Essence",
                            Price = 89.99m
                        },
                        new
                        {
                            Id = 2,
                            Details = "Nocna maska intensywnie nawilżająca.",
                            ImageUrl = "https://example.com/laneige-mask.jpg",
                            IsTrendingProduct = true,
                            Name = "Laneige Water Sleeping Mask",
                            Price = 129.99m
                        },
                        new
                        {
                            Id = 3,
                            Details = "Serum z zieloną herbatą wzmacniające barierę skóry.",
                            ImageUrl = "https://example.com/innisfree-serum.jpg",
                            IsTrendingProduct = false,
                            Name = "Innisfree Green Tea Seed Serum",
                            Price = 119.99m
                        },
                        new
                        {
                            Id = 4,
                            Details = "Lekki krem przeciwsłoneczny z ekstraktami roślinnymi.",
                            ImageUrl = "https://example.com/joseon-sunscreen.jpg",
                            IsTrendingProduct = true,
                            Name = "Beauty of Joseon Relief Sun SPF50+",
                            Price = 69.99m
                        },
                        new
                        {
                            Id = 5,
                            Details = "Krem regenerujący dla skóry bardzo wrażliwej.",
                            ImageUrl = "https://example.com/soonjung-cream.jpg",
                            IsTrendingProduct = false,
                            Name = "Etude House SoonJung 2x Barrier Cream",
                            Price = 79.99m
                        },
                        new
                        {
                            Id = 6,
                            Details = "Krem kojący redukujący zaczerwienienia.",
                            ImageUrl = "https://example.com/drjart-cicapair.jpg",
                            IsTrendingProduct = true,
                            Name = "Dr. Jart+ Cicapair Tiger Grass Cream",
                            Price = 159.99m
                        },
                        new
                        {
                            Id = 7,
                            Details = "Esencja anti-aging poprawiająca strukturę skóry.",
                            ImageUrl = "https://example.com/missha-essence.jpg",
                            IsTrendingProduct = false,
                            Name = "Missha Time Revolution First Treatment Essence",
                            Price = 139.99m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
