// <auto-generated />
using KoreanSkincareShop.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KoreanSkincareShop.Migrations
{
    [DbContext(typeof(SkincareShopDbContext))]
    [Migration("20260105135031_ShoppingCartItemAdded")]
    partial class ShoppingCartItemAdded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KoreanSkincareShop.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsTrendingProduct")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Details = "Overnight calming mask with cica and niacinamide that helps reduce irritation and restore skin balance.",
                            ImageUrl = "/images/products/mediheal-cica-ac-calming-sleeping-mask.webp",
                            IsTrendingProduct = true,
                            Name = "Mediheal Cica AC Calming Sleeping Mask",
                            Price = 12.99m
                        },
                        new
                        {
                            Id = 2,
                            Details = "Firming toner pads infused with collagen to improve skin elasticity and hydration.",
                            ImageUrl = "/images/products/mediheal-collagen-ampoule-pad.jpg",
                            IsTrendingProduct = true,
                            Name = "Mediheal Collagen Ampoule Pad",
                            Price = 119.99m
                        },
                        new
                        {
                            Id = 3,
                            Details = "Targeted blemish patches with madecassoside to calm and protect irritated skin.",
                            ImageUrl = "/images/products/mediheal-derma-clear-madecassoside-patch.webp",
                            IsTrendingProduct = false,
                            Name = "Mediheal Derma Clear Madecassoside Patch",
                            Price = 25.99m
                        },
                        new
                        {
                            Id = 4,
                            Details = "Alginate modeling mask with madecassoside for intensive soothing and regeneration.",
                            ImageUrl = "/images/products/mediheal-derma-modeling-madecassoside-mask.webp",
                            IsTrendingProduct = false,
                            Name = "Mediheal Derma Modeling Madecassoside Mask",
                            Price = 31.99m
                        },
                        new
                        {
                            Id = 5,
                            Details = "Purifying alginate mask with tea tree extract for oily and blemish-prone skin.",
                            ImageUrl = "/images/products/mediheal-derma-modeling-teatree-mask.webp",
                            IsTrendingProduct = false,
                            Name = "Mediheal Derma Modeling Teatree Mask",
                            Price = 31.99m
                        },
                        new
                        {
                            Id = 6,
                            Details = "Set of five essential Mediheal sheet masks for different skin needs.",
                            ImageUrl = "/images/products/mediheal-essential-mask-set.webp",
                            IsTrendingProduct = true,
                            Name = "Mediheal Essential Mask Set",
                            Price = 53.99m
                        },
                        new
                        {
                            Id = 7,
                            Details = "Soothing toner pads with madecassoside to reduce redness and improve skin texture.",
                            ImageUrl = "/images/products/mediheal-madecassoside-blemish-pad.jpg",
                            IsTrendingProduct = true,
                            Name = "Mediheal Madecassoside Blemish Pad",
                            Price = 119.99m
                        },
                        new
                        {
                            Id = 8,
                            Details = "Regenerating sheet mask with madecassoside for sensitive and irritated skin.",
                            ImageUrl = "/images/products/mediheal-madecassoside-essential-mask.webp",
                            IsTrendingProduct = false,
                            Name = "Mediheal Madecassoside Essential Mask",
                            Price = 7.99m
                        },
                        new
                        {
                            Id = 9,
                            Details = "Deeply moisturizing sheet mask with panthenol to strengthen the skin barrier.",
                            ImageUrl = "/images/products/mediheal-nmf-panthenol-mask.webp",
                            IsTrendingProduct = false,
                            Name = "Mediheal N.M.F Panthenol Mask",
                            Price = 9.99m
                        },
                        new
                        {
                            Id = 10,
                            Details = "Daily calming sheet mask designed to soothe sensitive and stressed skin.",
                            ImageUrl = "/images/products/mediheal-pure-calming-mask.jpg",
                            IsTrendingProduct = true,
                            Name = "Mediheal Pure Calming Mask",
                            Price = 5.99m
                        },
                        new
                        {
                            Id = 11,
                            Details = "Bamboo sheet mask with tea tree extract to calm and purify the skin.",
                            ImageUrl = "/images/products/mediheal-teatree-essential-mask.webp",
                            IsTrendingProduct = true,
                            Name = "Mediheal Teatree Essential Mask",
                            Price = 5.95m
                        },
                        new
                        {
                            Id = 12,
                            Details = "Hydrogel calming mask with tea tree for instant soothing effect.",
                            ImageUrl = "/images/products/mediheal-teatree-nude-gel-mask.jpg",
                            IsTrendingProduct = false,
                            Name = "Mediheal Teatree Nude Gel Mask",
                            Price = 10.99m
                        },
                        new
                        {
                            Id = 13,
                            Details = "Exfoliating and calming pads with tea tree extract for troubled skin.",
                            ImageUrl = "/images/products/mediheal-teatree-trouble-pad.jpg",
                            IsTrendingProduct = true,
                            Name = "Mediheal Teatree Trouble Pad",
                            Price = 119.99m
                        },
                        new
                        {
                            Id = 14,
                            Details = "Soothing sheet mask combining tea tree and cica for irritated skin.",
                            ImageUrl = "/images/products/mediheal-teatree-x-cica-mask.webp",
                            IsTrendingProduct = false,
                            Name = "Mediheal Teatree X Cica Mask",
                            Price = 9.99m
                        },
                        new
                        {
                            Id = 15,
                            Details = "Calming bamboo sheet mask with tea tree extract, ideal for sensitive and irritated skin.",
                            ImageUrl = "/images/products/mediheal-teatree-essential-mask.jpg",
                            IsTrendingProduct = true,
                            Name = "Mediheal Teatree Essential Bamboo Mask",
                            Price = 7.99m
                        });
                });

            modelBuilder.Entity("KoreanSkincareShop.Models.ShoppingCartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.Property<string>("ShoppingCardId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ShoppingCartItems");
                });

            modelBuilder.Entity("KoreanSkincareShop.Models.ShoppingCartItem", b =>
                {
                    b.HasOne("KoreanSkincareShop.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId");

                    b.Navigation("Product");
                });
#pragma warning restore 612, 618
        }
    }
}
